pipeline {
  agent {
    kubernetes {
      // Define the pod template with container template
      containerTemplate {
            name 'gradle'
            image 'gradle'
            command 'sleep'
            args '30d'
        }
    }
  }

  //prepare environment 
  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/bufferbox/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
        sh '''
          chmod +x gradlew
        '''
      }
    }

    //run tests on main branch
    stage('Code coverage') {
      when {
        // Run CodeCoverage test only on the main branch
              branch 'main'
            }
      steps{
        echo 'Code coverage on main branch'
        sh '''
          pwd
          ./gradlew jacocoTestCoverageVerification
         '''
      }
    }

    //run tests on all other branches
    stage('Run Unit test and Checkstyle - all other branches') {
      when {
        not { branch 'main' }
      }
      steps {
         echo 'Unit test not main branch'
         sh '''
           pwd
           ./gradlew test
           ./gradlew checkstyleMain
         '''
      }
    }
  }
}
