pipeline {
  agent {
    kubernetes {
      // Define the pod template with container template
      podTemplate {
        // Define the container template
        containers {
          containerTemplate {
            name 'gradle'
            image 'gradle'
            command 'sleep'
            args '30d'
          }
        }
        // Label the pod
        label 'POD_LABEL'
      }
    }
  }
  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
        sh """
          cd Chapter08/sample1
          chmod +x gradlew
        """
      }
    }
    stage('Run pipeline against a gradle project - test MAIN') {
      when {
        not { branch 'main' }
      }
      steps {
        container('gradle') {
          steps {
            echo 'Unit test not main branch'
            sh "./gradlew test"
          }
        }
      }
    }
  }
}
